=== zenden2k/uptooda/Data/servers.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified"
           elementFormDefault="qualified">
    <xs:simpleType name="ActionType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="get" />
            <xs:enumeration value="post" />
            <xs:enumeration value="put" />
            <xs:enumeration value="patch" />
            <xs:enumeration value="delete" />
            <xs:enumeration value="head" />
            <xs:enumeration value="options" />
            <xs:enumeration value="login" />
            <xs:enumeration value="upload" />
            <xs:enumeration value="openurl" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Bool">
        <xs:restriction base="xs:string">
            <xs:enumeration value="1"/>
            <xs:enumeration value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="StorageTimeType">
        <xs:restriction base="xs:token">
            <xs:pattern value="-1|[0-9]+|[0-9]+h"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="AuthorizeType">
        <xs:restriction base="xs:byte">
            <xs:enumeration value="0" />
            <xs:enumeration value="1" />
            <xs:enumeration value="2" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ServerType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="file" />
            <xs:enumeration value="image" />
            <xs:enumeration value="urlshortening" />
            <xs:enumeration value="searchbyimage" />
            <xs:enumeration value="video" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ServerTypes">
        <xs:restriction>
            <xs:simpleType>
                <xs:list>
                    <xs:simpleType>
                        <xs:restriction base="xs:token">
                            <xs:enumeration value="file"/>
                            <xs:enumeration value="image"/>
                            <xs:enumeration value="urlshortening"/>
                            <xs:enumeration value="video"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:list>
            </xs:simpleType>
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="DefaultForTypes">
        <xs:restriction>
            <xs:simpleType>
                <xs:list>
                    <xs:simpleType>
                        <xs:restriction base="xs:token">
                            <xs:enumeration value="file"/>
                            <xs:enumeration value="image"/>
                            <xs:enumeration value="urlshortening"/>
                            <xs:enumeration value="searchbyimage"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:list>
            </xs:simpleType>
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="AssignVarsType">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-z0-9_]+:\d+)*(;[A-z0-9_]+:\d+)*;?"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="MinVersionType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d+\.\d+\.\d+(\.\d+)?"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="CustomHeadersType">
        <xs:restriction base="xs:string">
            <!--<xs:pattern value="[A-z0-9_]+:(;[A-z0-9_]+:.+?)*;?"/>--> <!-- TODO: write correct regexp -->
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="Servers">
        <xs:complexType>
            <xs:sequence>
               <xs:element name="Server" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:all> 
                            <xs:element name="Info" minOccurs="0">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="SupportedFormats" minOccurs="0">
                                            <xs:complexType mixed="true">
                                                <xs:sequence>
                                                    <xs:element name="FormatGroup" maxOccurs="unbounded" minOccurs="1">
                                                        <xs:complexType mixed="true">
                                                            <xs:sequence>
                                                                <xs:element name="Format" maxOccurs="unbounded" minOccurs="1">
                                                                    <xs:complexType>
                                                                        <xs:simpleContent>
                                                                            <xs:extension base="xs:string">
                                                                                <xs:attribute type="xs:integer" name="MaxFileSize" use="optional"/>
                                                                                <xs:attribute type="xs:string" name="MimeType" use="optional"/>
                                                                            </xs:extension>
                                                                        </xs:simpleContent>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute type="xs:integer" name="MaxFileSize" use="optional"/>
                                                            <xs:attribute type="xs:string" name="UserTypes" use="optional"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="StorageTimeInfo" minOccurs="0">
                                            <xs:complexType mixed="true">
                                                <xs:sequence>
                                                    <xs:element name="StorageTime" maxOccurs="unbounded" minOccurs="1">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="StorageTimeType">
                                                                    <xs:attribute type="Bool" name="AfterLastDownload" use="optional"/>
                                                                    <xs:attribute type="xs:string" name="UserTypes" use="optional"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>        
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="ForbiddenFormats" minOccurs="0">
                                            <xs:complexType mixed="true">
                                                <xs:sequence>
                                                    <xs:element name="FormatGroup" maxOccurs="unbounded" minOccurs="1">
                                                        <xs:complexType mixed="true">
                                                            <xs:sequence>
                                                                <xs:element name="Format" maxOccurs="unbounded" minOccurs="1">
                                                                    <xs:complexType>
                                                                        <xs:simpleContent>
                                                                            <xs:extension base="xs:string">
                                                                                <xs:attribute type="xs:integer" name="MaxFileSize" use="optional"/>
                                                                                <xs:attribute type="xs:string" name="MimeType" use="optional"/>
                                                                            </xs:extension>
                                                                        </xs:simpleContent>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute type="xs:integer" name="MaxFileSize" use="optional"/>
                                                            <xs:attribute type="xs:string" name="UserTypes" use="optional"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>    
                            </xs:element>
                            <xs:element name="Actions" minOccurs="0">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="Action" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType mixed="true">
                                                <xs:choice maxOccurs="unbounded">
                                                    <xs:element name="Body" maxOccurs="unbounded" minOccurs="0" type="xs:string"/>
                                                    <xs:element name="RegExp" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute type="xs:string" name="Pattern"
                                                                                  use="required"/>
                                                                    <xs:attribute type="xs:string" name="Data"
                                                                                  use="optional"/>
                                                                    <xs:attribute type="AssignVarsType" name="AssignVars"
                                                                                  use="optional"/>
                                                                    <xs:attribute type="xs:byte" name="Required"
                                                                                  use="optional" default="1"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Call" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute type="xs:string" name="Function"
                                                                                  use="required"/>
                                                                    <xs:attribute type="xs:string" name="Arg1"
                                                                                  use="optional"/>
                                                                    <xs:attribute type="AssignVarsType" name="AssignVars"
                                                                                  use="optional"/>
                                                                    <xs:attribute type="xs:byte" name="Required"
                                                                                  use="optional" default="1"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:choice>
                                                <xs:attribute type="ActionType" name="Type" use="optional"/>
                                                <xs:attribute type="xs:string" name="Url" use="optional"/>
                                                <xs:attribute type="xs:string" name="PostParams" use="optional"/>
                                                <xs:attribute type="Bool" name="OnlyOnce" use="optional"/>
                                                <xs:attribute type="xs:string" name="RegExp" use="optional"/>
                                                <xs:attribute type="xs:string" name="AssignVars" use="optional"/>
                                                <xs:attribute type="xs:anyURI" name="Referer" use="optional"/>
                                                <xs:attribute type="CustomHeadersType" name="CustomHeaders" use="optional"/>
                                                <xs:attribute type="xs:string" name="Description" use="optional"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Result" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="ImageUrlTemplate" use="optional"/>
                                            <xs:attribute type="xs:string" name="ThumbUrlTemplate" use="optional"/>
                                            <xs:attribute type="xs:string" name="DeleteUrl" use="optional"/>
                                            <xs:attribute type="xs:string" name="DownloadUrlTemplate" use="optional"/>
                                            <xs:attribute type="xs:string" name="DownloadUrl" use="optional"/>
                                            <xs:attribute type="xs:string" name="DirectUrlTemplate" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                        <xs:attribute type="xs:string" name="Name" use="required"/>
                        <xs:attribute type="xs:string" name="DisplayName" use="optional"/>
                        <xs:attribute type="xs:integer" name="MaxFileSize" use="optional"/>
                        <xs:attribute type="Bool" name="Debug" use="optional"/>
                        <xs:attribute type="AuthorizeType" name="Authorize" use="optional"/>
                        <xs:attribute type="xs:string" name="Plugin" use="optional"/>
                        <xs:attribute type="xs:positiveInteger" name="MaxThreads" use="optional"/>
                        <xs:attribute type="Bool" name="NeedPassword" use="optional"/>
                        <xs:attribute type="Bool" name="SupportsFolders" use="optional"/>
                        <xs:attribute type="xs:anyURI" name="RegistrationUrl" use="optional"/>
                        <xs:attribute type="xs:anyURI" name="WebsiteUrl" use="optional"/>
                        <xs:attribute type="xs:byte" name="FileHost" use="optional"/>
                        <xs:attribute type="ServerType" name="Type" use="optional"/>
                        <xs:attribute type="ServerTypes" name="Types" use="optional"/>
                        <xs:attribute type="xs:string" name="LoginLabel" use="optional"/>
                        <xs:attribute type="xs:string" name="PasswordLabel" use="optional"/>
                        <xs:attribute type="DefaultForTypes" name="DefaultForTypes" use="optional"/> 
                        <xs:attribute type="Bool" name="UploadToTempServer" use="optional"/>  
                        <xs:attribute type="MinVersionType" name="MinVersion" use="optional"/>  
                        <xs:attribute type="xs:string" name="Engine" use="optional"/>
                        <xs:attribute type="xs:string" name="UserAgent" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== zenden2k/uptooda/Source/Tests/TestData/servers.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Servers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="servers.xsd">
	<Server Name="radikal.ru" MaxFileSize="10000000" Debug="0" Authorize="1" Plugin="radikal">
		<Info>
			<SupportedFormats>
				<FormatGroup>
					<Format MimeType="image/jpeg" MaxFileSize="3000000">*.jpg,*.jpeg</Format>
					<Format MimeType="image/png">*.png</Format>
					<Format MimeType="image/gif">*.gif</Format>
					<Format MimeType="image/webp">*.webp</Format>
					<Format MimeType="image/tiff">*.tiff</Format>
				</FormatGroup>
				<FormatGroup>
					<Format MimeType="video/mp4">*.mp4</Format>
					<Format MimeType="video/webm">*.webm</Format>
					<Format MimeType="video/mpeg">*.mpeg,*.vob</Format>
					<Format MimeType="video/x-msvideo">*.avi</Format>
					<Format MimeType="video/quicktime">*.mov</Format>
					<Format MimeType="video/x-matroska">*.mkv</Format>
					<Format MimeType="video/x-flv">*.flv</Format>
					<Format MimeType="video/x-ms-wmv">*.wmv</Format>
				</FormatGroup>		 
			</SupportedFormats>
			<StorageTimeInfo>
				<StorageTime UserTypes="anon">2</StorageTime>
				<StorageTime UserTypes="reg">36h</StorageTime>
			</StorageTimeInfo>
		</Info>
		<Actions>
			<Action Type="login" Url="http://radikal.ru/Auth/Login" PostParams="Login=$(_LOGIN);Password=$(_PASSWORD);IsRemember=true;ReturnUrl=/;" OnlyOnce="1"/>
			<Action Type="upload" Url="http://radikal.ru/api3/rest/uplimg/prepared" PostParams="RESPTYPE=xml;FROMOBJECT=22;MAXSIZEIMG=1024;MAXSIZEIMGPREV=$(_THUMBWIDTH);ISINSCRIMGPREV=true;INSCRIMGPREV=Увеличить;IDALBUM=noall;COMMENTIMG=;URLFORIMG=;TAGS=;ISPUBLIC=false;Filename=$(_FILENAME);Filedata=%filename%;Upload=Submit Query" RegExp='&lt;ImgPreviewUrl&gt;(.*?)&lt;([\s\S]*?)&lt;ImgUrl&gt;(.*?)&lt;' AssignVars="Image:2;Thumb:0" Referer="http://radikal.ru/Content/Clients/FotoFlashApplet3.swf?v=13"/>
		</Actions>
		<Result ImageUrlTemplate="$(Image)" ThumbUrlTemplate="$(Thumb)"/>
	</Server>
	<Server Name="fastpic.ru" MaxFileSize="10737418240" Debug="1" DefaultForTypes="image" MinVersion="1.3.3">
		<Actions>
			<Action Type="upload" Url="http://fastpic.ru/upload?api=1" PostParams="method=file;file1=%filename%;check_thumb=size;uploading=1;orig_rotate=0;thumb_size=$(_THUMBWIDTH)" RegExp='&lt;imagepath&gt;(.*?)&lt;\/imagepath&gt;([\s\S]*?)&lt;thumbpath&gt;(.*?)&lt;\/thumbpath&gt;' AssignVars="Image:0;Thumb:2">
				<RegExp Pattern="&lt;viewurl&gt;(.*?)&lt;\/viewurl&gt;" AssignVars="DownloadUrl:0;"/>
				<Call Function="json" Arg0="test" AssignVars="DownloadUrl:0;"/>
			</Action>
		</Actions>
		<Result ImageUrlTemplate="$(Image)" ThumbUrlTemplate="$(Thumb)" DownloadUrl="$(DownloadUrl)" />
	</Server>
	<Server2 Name="8b.kz" Authorize="0" Types="image urlshortening" DefaultForTypes="urlshortening" RetryLimit="3">
		<Actions>
			<Action 
				Type="post"
				Url="http://8b.kz/ajax/new_url"
				PostParams="custom=;url=$(_ORIGINALURL|urlencode)"
				Referer="http://8b.kz/"
				RegExp='"key":"((\\"|[^"])*)"'
				AssignVars="surl:0"
				
			/>
		</Actions>
		<Result DirectUrlTemplate="http://8b.kz/$(surl)" />
	</Server2>
	<Server2 Name="test.com" Authorize="0" Type="image">
		<Actions>
			<Action 
				Type="post"
				Url="http://8b.kz/ajax/new_url"
				PostParams="custom=;url=$(_ORIGINALURL|urlencode)"
				Referer="http://8b.kz/"
				RegExp='"key":"((\\"|[^"])*)"'
				AssignVars="surl:0"
				RetryLimit="3"
			/>
		</Actions>
		<Result DirectUrlTemplate="http://8b.kz/$(surl)" />
	</Server2>
	<Server2 Name="Test directory" Plugin="directory">
		<Actions>
		</Actions>
		<Result DirectUrlTemplate="stub" />
	</Server2>
	<Server2 Name="Test Hidden" MinVersion="9999999.0.0">
		<Actions>
		</Actions>
		<Result DirectUrlTemplate="stub" />
	</Server2>
	<!--<Server2 Name="Test Ftp" Plugin="ftp" FileHost="1">
		<Actions>
		</Actions>
		<Result DirectUrlTemplate="stub" />
	</Server2>-->
</Servers>
